# Color scheme
include ~/.cache/wal/colors-kitty.conf 

# Font settings
font_family JetBrains Mono
bold_font JetBrains Mono Bold


# Background and transparency
background_opacity 0.5

# Window settings
confirm_os_window_close 0

# Cursor settings
cursor_shape beam
cursor_trail 1

# Shell and other settings
shell /usr/bin/zsh
# enable_graphics yes
window_padding_width 5 10

# limiting the scroll backlines
# scrollback_lines 2000

