#################
### AUTOSTART ###
#################

xwayland {
  force_zero_scaling = true
}

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle
exec-once = nm-applet
exec-once = swaync
exec-once = sleep 1 && waybar
exec-once = awww-daemon & sleep 1
